
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 30 01:08:11 GMT-03:00 2011
//----------------------------------------------------

package analise_sintatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 36;
  public static final int LEFT_BRK = 12;
  public static final int GE = 21;
  public static final int XOR = 27;
  public static final int INTEGER = 37;
  public static final int LEFT_BRA = 13;
  public static final int COLLECTIONOPERATION = 17;
  public static final int MINUS = 34;
  public static final int BAR = 42;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int LT = 23;
  public static final int OR = 25;
  public static final int COMMA = 8;
  public static final int IMPLIES = 28;
  public static final int COLLECTION = 6;
  public static final int PLUS = 33;
  public static final int IF = 29;
  public static final int DOT = 7;
  public static final int CONTEXT = 4;
  public static final int LE = 20;
  public static final int BOOLEAN = 41;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int EQ = 18;
  public static final int RIGHT_PAR = 14;
  public static final int REAL = 38;
  public static final int ENDPACKAGE = 3;
  public static final int TIMES = 35;
  public static final int COLON = 9;
  public static final int PATHNAME = 10;
  public static final int ENDIF = 32;
  public static final int ELSE = 30;
  public static final int PACKAGE = 2;
  public static final int RIGHT_BRK = 15;
  public static final int THEN = 31;
  public static final int BODY = 5;
  public static final int NE = 19;
  public static final int STRING = 39;
  public static final int RIGHT_BRA = 16;
  public static final int LEFT_PAR = 11;
  public static final int GT = 22;
  public static final int IDENTIFIER = 40;
}

