
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 02 15:37:51 GMT-03:00 2011
//----------------------------------------------------

package util;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 38;
  public static final int LEFT_BRK = 13;
  public static final int GE = 23;
  public static final int XOR = 29;
  public static final int INTEGER = 43;
  public static final int LEFT_BRA = 14;
  public static final int COLLECTIONOPERATION = 19;
  public static final int MINUS = 36;
  public static final int BAR = 18;
  public static final int NOT = 28;
  public static final int AND = 26;
  public static final int LT = 25;
  public static final int OR = 27;
  public static final int COMMA = 9;
  public static final int IMPLIES = 30;
  public static final int COLLECTION = 6;
  public static final int PLUS = 35;
  public static final int IF = 31;
  public static final int DOT = 8;
  public static final int CONTEXT = 4;
  public static final int LE = 22;
  public static final int BOOLEAN = 47;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int SELF = 7;
  public static final int BOOLEANTYPE = 41;
  public static final int EQ = 20;
  public static final int RIGHT_PAR = 15;
  public static final int REAL = 44;
  public static final int REALTYPE = 40;
  public static final int ENDPACKAGE = 3;
  public static final int TIMES = 37;
  public static final int COLON = 10;
  public static final int PATHNAME = 11;
  public static final int ENDIF = 34;
  public static final int ELSE = 32;
  public static final int PACKAGE = 2;
  public static final int STRINGTYPE = 42;
  public static final int RIGHT_BRK = 16;
  public static final int THEN = 33;
  public static final int BODY = 5;
  public static final int NE = 21;
  public static final int STRING = 45;
  public static final int RIGHT_BRA = 17;
  public static final int LEFT_PAR = 12;
  public static final int GT = 24;
  public static final int INTEGERTYPE = 39;
  public static final int IDENTIFIER = 46;
}

