/* The following code was generated by JFlex 1.4.3 on 04/03/11 17:58 */

package ClassesJava;

import java_cup.runtime.*; 
import java_cup.runtime.Symbol;
import java_cup.sym; 


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 04/03/11 17:58 from the specification file
 * <tt>C:/Users/Natã/Desktop/UFCG/Disciplinas/Compiladores/Projeto/workspace/analise_lexica_OCL/src/flex/analiseOCL.flex</tt>
 */
class AnaliseLexicaOCL implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\1\1\0\1\3\1\2\22\0\1\3\6\0\1\14"+
    "\1\17\1\22\1\5\1\13\1\25\1\6\1\11\1\4\12\7\1\15"+
    "\1\26\1\33\1\32\1\34\1\31\1\30\1\10\1\53\1\56\1\10"+
    "\1\12\11\10\1\61\3\10\1\52\1\63\6\10\1\20\1\0\1\23"+
    "\1\16\1\10\1\0\1\36\1\50\1\37\1\44\1\42\1\64\1\41"+
    "\1\65\1\60\1\10\1\40\1\57\1\67\1\43\1\45\1\35\1\54"+
    "\1\62\1\66\1\46\1\55\1\70\1\10\1\47\1\51\1\10\1\21"+
    "\1\27\1\24\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\3\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\1\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\22\7\2\0\1\32\2\0\1\33"+
    "\1\0\1\34\1\35\1\36\1\37\1\40\1\41\7\7"+
    "\1\42\7\7\1\43\5\7\1\0\1\44\1\0\1\44"+
    "\1\7\1\45\3\7\1\46\1\47\2\7\1\50\1\7"+
    "\1\51\6\7\1\52\4\7\1\53\1\54\1\55\1\56"+
    "\11\7\1\57\4\7\1\60\1\61\10\7\1\62\1\63"+
    "\3\7\1\64\11\7\1\60\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\71\0\344\0\71\0\u011d"+
    "\0\u0156\0\u018f\0\u01c8\0\71\0\u0201\0\u023a\0\u0273\0\71"+
    "\0\71\0\71\0\71\0\71\0\71\0\71\0\71\0\71"+
    "\0\71\0\71\0\71\0\u02ac\0\u02e5\0\u031e\0\u0357\0\u0390"+
    "\0\u03c9\0\u0402\0\u043b\0\u0474\0\u04ad\0\u04e6\0\u051f\0\u0558"+
    "\0\u0591\0\u05ca\0\u0603\0\u063c\0\u0675\0\u06ae\0\u06e7\0\u0720"+
    "\0\u0759\0\71\0\u0792\0\u07cb\0\71\0\u0201\0\71\0\71"+
    "\0\71\0\71\0\71\0\71\0\u0804\0\u083d\0\u0876\0\u08af"+
    "\0\u08e8\0\u0921\0\u095a\0\u018f\0\u0993\0\u09cc\0\u0a05\0\u0a3e"+
    "\0\u0a77\0\u0ab0\0\u0ae9\0\u018f\0\u0b22\0\u0b5b\0\u0b94\0\u0bcd"+
    "\0\u0c06\0\u0c3f\0\u0c78\0\u0cb1\0\u0cb1\0\u0cea\0\u018f\0\u0d23"+
    "\0\u0d5c\0\u0d95\0\u018f\0\u018f\0\u0dce\0\u0e07\0\u018f\0\u0e40"+
    "\0\u018f\0\u0e79\0\u0eb2\0\u0eeb\0\u0f24\0\u0f5d\0\u0f96\0\u018f"+
    "\0\u0fcf\0\u1008\0\u1041\0\u107a\0\u018f\0\u018f\0\u018f\0\u018f"+
    "\0\u10b3\0\u10ec\0\u1125\0\u115e\0\u1197\0\u11d0\0\u1209\0\u1242"+
    "\0\u127b\0\u018f\0\u12b4\0\u12ed\0\u1326\0\u135f\0\u1398\0\u018f"+
    "\0\u13d1\0\u140a\0\u1443\0\u147c\0\u14b5\0\u14ee\0\u1527\0\u1560"+
    "\0\u018f\0\u018f\0\u1599\0\u15d2\0\u160b\0\u018f\0\u1644\0\u167d"+
    "\0\u16b6\0\u16ef\0\u1728\0\u1761\0\u179a\0\u17d3\0\u180c\0\u018f"+
    "\0\u018f";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\12\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\2\12\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\12\1\50\1\51\2\12\1\52\1\12\1\53\1\54"+
    "\1\12\1\55\1\56\2\12\1\57\1\12\73\0\1\5"+
    "\67\0\1\5\74\0\1\60\71\0\1\61\25\0\1\62"+
    "\43\0\1\11\1\0\1\63\1\64\27\0\1\64\35\0"+
    "\2\12\1\0\1\12\22\0\34\12\11\0\1\65\57\0"+
    "\14\66\1\67\54\66\15\0\1\70\71\0\1\71\104\0"+
    "\1\72\1\0\1\73\66\0\1\74\45\0\2\12\1\0"+
    "\1\12\22\0\1\12\1\75\32\12\7\0\2\12\1\0"+
    "\1\12\22\0\6\12\1\76\25\12\7\0\2\12\1\0"+
    "\1\12\22\0\10\12\1\77\23\12\7\0\2\12\1\0"+
    "\1\12\22\0\6\12\1\100\13\12\1\101\11\12\7\0"+
    "\2\12\1\0\1\12\22\0\10\12\1\102\23\12\7\0"+
    "\2\12\1\0\1\12\22\0\23\12\1\103\10\12\7\0"+
    "\2\12\1\0\1\12\22\0\25\12\1\104\6\12\7\0"+
    "\2\12\1\0\1\12\22\0\25\12\1\105\2\12\1\106"+
    "\3\12\7\0\2\12\1\0\1\12\22\0\10\12\1\107"+
    "\23\12\7\0\2\12\1\0\1\12\22\0\10\12\1\110"+
    "\23\12\7\0\2\12\1\0\1\12\22\0\5\12\1\111"+
    "\26\12\7\0\2\12\1\0\1\12\22\0\1\12\1\112"+
    "\32\12\7\0\2\12\1\0\1\12\22\0\10\12\1\113"+
    "\23\12\7\0\2\12\1\0\1\12\22\0\27\12\1\114"+
    "\2\12\1\115\1\12\7\0\2\12\1\0\1\12\22\0"+
    "\25\12\1\116\6\12\7\0\2\12\1\0\1\12\22\0"+
    "\20\12\1\117\13\12\7\0\2\12\1\0\1\12\22\0"+
    "\1\12\1\120\32\12\7\0\2\12\1\0\1\12\22\0"+
    "\10\12\1\121\23\12\5\60\1\122\63\60\1\61\1\3"+
    "\1\4\66\61\7\0\1\123\67\0\1\124\1\125\3\0"+
    "\1\124\64\0\2\12\1\0\1\12\22\0\2\12\1\126"+
    "\31\12\7\0\2\12\1\0\1\12\22\0\7\12\1\127"+
    "\24\12\7\0\2\12\1\0\1\12\22\0\6\12\1\130"+
    "\25\12\7\0\2\12\1\0\1\12\22\0\7\12\1\131"+
    "\24\12\7\0\2\12\1\0\1\12\22\0\31\12\1\132"+
    "\2\12\7\0\2\12\1\0\1\12\22\0\11\12\1\133"+
    "\22\12\7\0\2\12\1\0\1\12\22\0\33\12\1\134"+
    "\7\0\2\12\1\0\1\12\22\0\20\12\1\135\13\12"+
    "\7\0\2\12\1\0\1\12\22\0\5\12\1\136\26\12"+
    "\7\0\2\12\1\0\1\12\22\0\25\12\1\137\6\12"+
    "\7\0\2\12\1\0\1\12\22\0\7\12\1\140\24\12"+
    "\7\0\2\12\1\0\1\12\22\0\11\12\1\141\5\12"+
    "\1\142\14\12\7\0\2\12\1\0\1\12\22\0\4\12"+
    "\1\141\27\12\7\0\2\12\1\0\1\12\22\0\22\12"+
    "\1\143\11\12\7\0\2\12\1\0\1\12\22\0\1\144"+
    "\33\12\7\0\2\12\1\0\1\12\22\0\7\12\1\145"+
    "\24\12\7\0\2\12\1\0\1\12\22\0\1\146\33\12"+
    "\7\0\2\12\1\0\1\12\22\0\22\12\1\147\11\12"+
    "\7\0\2\12\1\0\1\12\22\0\7\12\1\150\24\12"+
    "\4\60\1\5\1\122\63\60\7\0\1\123\2\0\1\64"+
    "\27\0\1\64\35\0\1\125\70\0\2\12\1\0\1\12"+
    "\22\0\3\12\1\151\30\12\7\0\2\12\1\0\1\12"+
    "\22\0\11\12\1\152\22\12\7\0\2\12\1\0\1\12"+
    "\22\0\1\153\22\12\1\154\10\12\7\0\2\12\1\0"+
    "\1\12\22\0\5\12\1\155\26\12\7\0\2\12\1\0"+
    "\1\12\22\0\5\12\1\156\26\12\7\0\2\12\1\0"+
    "\1\12\22\0\6\12\1\157\25\12\7\0\2\12\1\0"+
    "\1\12\22\0\14\12\1\160\17\12\7\0\2\12\1\0"+
    "\1\12\22\0\20\12\1\161\13\12\7\0\2\12\1\0"+
    "\1\12\22\0\22\12\1\162\11\12\7\0\2\12\1\0"+
    "\1\12\22\0\22\12\1\163\11\12\7\0\2\12\1\0"+
    "\1\12\22\0\5\12\1\164\26\12\7\0\2\12\1\0"+
    "\1\12\22\0\22\12\1\165\11\12\7\0\2\12\1\0"+
    "\1\12\22\0\31\12\1\166\2\12\7\0\2\12\1\0"+
    "\1\12\22\0\1\12\1\167\32\12\7\0\2\12\1\0"+
    "\1\12\22\0\5\12\1\170\26\12\7\0\2\12\1\0"+
    "\1\12\22\0\1\12\1\171\32\12\7\0\2\12\1\0"+
    "\1\12\22\0\27\12\1\172\4\12\7\0\2\12\1\0"+
    "\1\12\22\0\5\12\1\173\26\12\7\0\2\12\1\0"+
    "\1\12\22\0\5\12\1\174\26\12\7\0\2\12\1\0"+
    "\1\12\22\0\23\12\1\175\10\12\7\0\2\12\1\0"+
    "\1\12\22\0\25\12\1\176\6\12\7\0\2\12\1\0"+
    "\1\12\22\0\5\12\1\177\26\12\7\0\2\12\1\0"+
    "\1\12\22\0\5\12\1\200\26\12\7\0\2\12\1\0"+
    "\1\12\22\0\4\12\1\201\27\12\7\0\2\12\1\0"+
    "\1\12\22\0\12\12\1\202\21\12\7\0\2\12\1\0"+
    "\1\12\22\0\2\12\1\203\31\12\7\0\2\12\1\0"+
    "\1\12\22\0\6\12\1\204\25\12\7\0\2\12\1\0"+
    "\1\12\22\0\2\12\1\205\31\12\7\0\2\12\1\0"+
    "\1\12\22\0\5\12\1\206\26\12\7\0\2\12\1\0"+
    "\1\12\22\0\5\12\1\207\26\12\7\0\2\12\1\0"+
    "\1\12\22\0\26\12\1\210\5\12\7\0\2\12\1\0"+
    "\1\12\22\0\5\12\1\211\26\12\7\0\2\12\1\0"+
    "\1\12\22\0\11\12\1\212\22\12\7\0\2\12\1\0"+
    "\1\12\22\0\3\12\1\213\30\12\7\0\2\12\1\0"+
    "\1\12\22\0\2\12\1\214\31\12\7\0\2\12\1\0"+
    "\1\12\22\0\11\12\1\215\22\12\7\0\2\12\1\0"+
    "\1\12\22\0\31\12\1\216\2\12\7\0\2\12\1\0"+
    "\1\12\22\0\7\12\1\217\24\12\7\0\2\12\1\0"+
    "\1\12\22\0\14\12\1\220\17\12\7\0\2\12\1\0"+
    "\1\12\22\0\1\12\1\221\32\12\7\0\2\12\1\0"+
    "\1\12\22\0\5\12\1\141\26\12\7\0\2\12\1\0"+
    "\1\12\22\0\23\12\1\222\10\12\7\0\2\12\1\0"+
    "\1\12\22\0\15\12\1\223\16\12\7\0\2\12\1\0"+
    "\1\12\22\0\1\224\33\12\7\0\2\12\1\0\1\12"+
    "\22\0\4\12\1\225\27\12\7\0\2\12\1\0\1\12"+
    "\22\0\10\12\1\226\23\12\7\0\2\12\1\0\1\12"+
    "\22\0\5\12\1\227\26\12\7\0\2\12\1\0\1\12"+
    "\22\0\5\12\1\230\26\12\7\0\2\12\1\0\1\12"+
    "\22\0\5\12\1\231\26\12\7\0\2\12\1\0\1\12"+
    "\22\0\6\12\1\141\25\12\7\0\2\12\1\0\1\12"+
    "\22\0\11\12\1\141\22\12";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6213];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\1\1\1\11\4\1\1\11"+
    "\3\1\14\11\24\1\2\0\1\11\2\0\1\11\1\0"+
    "\6\11\25\1\1\0\1\1\1\0\105\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	StringBuffer string = new StringBuffer();

	private Symbol symbol(int type) {
		System.out.println(yytext());
		Symbol symbol =  new Symbol(type, yyline, yycolumn); 
		return symbol;
	}
	private Symbol symbol(int type, Object value) {
		return new Symbol(type, yyline, yycolumn, value);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnaliseLexicaOCL(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  AnaliseLexicaOCL(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 146) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 20: 
          { return symbol(sym.BAR);
          }
        case 54: break;
        case 16: 
          { return symbol(sym.RIGHT_BRK);
          }
        case 55: break;
        case 14: 
          { return symbol(sym.LEFT_BRA);
          }
        case 56: break;
        case 30: 
          { return symbol(sym.UP_UP);
          }
        case 57: break;
        case 51: 
          { return symbol(sym.CONTEXT);
          }
        case 58: break;
        case 25: 
          { return symbol(sym.GT);
          }
        case 59: break;
        case 24: 
          { return symbol(sym.LT);
          }
        case 60: break;
        case 17: 
          { return symbol(sym.RIGHT_BRA);
          }
        case 61: break;
        case 38: 
          { return symbol(sym.NOT);
          }
        case 62: break;
        case 37: 
          { return symbol(sym.AND);
          }
        case 63: break;
        case 42: 
          { return symbol(sym.INT_MOD);
          }
        case 64: break;
        case 12: 
          { return symbol(sym.LEFT_PAR);
          }
        case 65: break;
        case 41: 
          { return symbol(sym.COLLECTION);
          }
        case 66: break;
        case 11: 
          { return symbol(sym.UP);
          }
        case 67: break;
        case 48: 
          { return symbol(sym.TUPLE);
          }
        case 68: break;
        case 39: 
          { return symbol(sym.INT_DIVIDE);
          }
        case 69: break;
        case 9: 
          { return symbol(sym.PLUS);
          }
        case 70: break;
        case 1: 
          { System.out.print(yytext());
          }
        case 71: break;
        case 44: 
          { return symbol(sym.TRUE);
          }
        case 72: break;
        case 15: 
          { return symbol(sym.RIGHT_PAR);
          }
        case 73: break;
        case 7: 
          { return symbol(sym.SIMPLE_NAME);
          }
        case 74: break;
        case 4: 
          { return symbol(sym.TIMES);
          }
        case 75: break;
        case 43: 
          { return symbol(sym.ELSE);
          }
        case 76: break;
        case 10: 
          { return symbol(sym.COLON);
          }
        case 77: break;
        case 22: 
          { return symbol(sym.QUESTION);
          }
        case 78: break;
        case 45: 
          { return symbol(sym.THEN);
          }
        case 79: break;
        case 35: 
          { return symbol(sym.IF);
          }
        case 80: break;
        case 52: 
          { return symbol(sym.IMPLIES);
          }
        case 81: break;
        case 47: 
          { return symbol(sym.ENDIF);
          }
        case 82: break;
        case 34: 
          { return symbol(sym.OR);
          }
        case 83: break;
        case 46: 
          { return symbol(sym.BODY);
          }
        case 84: break;
        case 23: 
          { return symbol(sym.EQ);
          }
        case 85: break;
        case 21: 
          { return symbol(sym.AT);
          }
        case 86: break;
        case 19: 
          { return symbol(sym.SEMICOLON);
          }
        case 87: break;
        case 50: 
          { return symbol(sym.PACKAGE);
          }
        case 88: break;
        case 32: 
          { return symbol(sym.NE);
          }
        case 89: break;
        case 6: 
          { return symbol(sym.INTEGER);
          }
        case 90: break;
        case 40: 
          { return symbol(sym.XOR);
          }
        case 91: break;
        case 26: 
          { return symbol(sym.MINUS_GT);
          }
        case 92: break;
        case 5: 
          { return symbol(sym.MINUS);
          }
        case 93: break;
        case 27: 
          { return symbol(sym.DOT_DOT);
          }
        case 94: break;
        case 33: 
          { return symbol(sym.GE);
          }
        case 95: break;
        case 28: 
          { return symbol(sym.STRING);
          }
        case 96: break;
        case 3: 
          { return symbol(sym.DIVIDE);
          }
        case 97: break;
        case 29: 
          { return symbol(sym.COLON_COLON);
          }
        case 98: break;
        case 18: 
          { return symbol(sym.COMMA);
          }
        case 99: break;
        case 2: 
          { /* Ignorar. */
          }
        case 100: break;
        case 13: 
          { return symbol(sym.LEFT_BRK);
          }
        case 101: break;
        case 36: 
          { return symbol(sym.REAL);
          }
        case 102: break;
        case 31: 
          { return symbol(sym.LE);
          }
        case 103: break;
        case 49: 
          { return symbol(sym.FALSE);
          }
        case 104: break;
        case 53: 
          { return symbol(sym.ENDPACKAGE);
          }
        case 105: break;
        case 8: 
          { return symbol(sym.DOT);
          }
        case 106: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java AnaliseLexicaOCL <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        AnaliseLexicaOCL scanner = null;
        try {
          scanner = new AnaliseLexicaOCL( new java.io.FileReader(argv[i]) );
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
