/* The following code was generated by JFlex 1.4.3 on 01/03/11 20:05 */
package ClassesJava;
import java_cup.sym;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 01/03/11 20:05 from the specification file
 * <tt>C:/Users/Natã/Desktop/UFCG/Disciplinas/Compiladores/Projeto/workspace/analise_lexica_OCL/src/flex/analiseOCL.flex</tt>
 */
class AnaliseLexicaOCL implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\24\1\3\1\1\1\0\1\3\1\2\16\24\4\0\1\3\3\0"+
    "\1\23\5\0\1\0\2\0\1\0\1\0\1\0\12\24\7\0\2\23"+
    "\1\10\27\23\4\0\1\23\1\0\1\15\1\23\1\21\1\23\1\7"+
    "\1\23\1\17\1\20\1\5\2\23\1\4\1\12\1\6\1\11\1\14"+
    "\1\23\1\16\1\23\1\13\3\23\1\22\2\23\4\0\41\24\2\0"+
    "\4\23\4\0\1\23\2\0\1\24\7\0\1\23\4\0\1\23\5\0"+
    "\27\23\1\0\37\23\1\0\u013f\23\31\0\162\23\4\0\14\23\16\0"+
    "\5\23\11\0\1\23\21\0\130\24\5\0\23\24\12\0\1\23\13\0"+
    "\1\23\1\0\3\23\1\0\1\23\1\0\24\23\1\0\54\23\1\0"+
    "\46\23\1\0\5\23\4\0\202\23\1\0\4\24\3\0\105\23\1\0"+
    "\46\23\2\0\2\23\6\0\20\23\41\0\46\23\2\0\1\23\7\0"+
    "\47\23\11\0\21\24\1\0\27\24\1\0\3\24\1\0\1\24\1\0"+
    "\2\24\1\0\1\24\13\0\33\23\5\0\3\23\15\0\4\24\14\0"+
    "\6\24\13\0\32\23\5\0\13\23\16\24\7\0\12\24\4\0\2\23"+
    "\1\24\143\23\1\0\1\23\10\24\1\0\6\24\2\23\2\24\1\0"+
    "\4\24\2\23\12\24\3\23\2\0\1\23\17\0\1\24\1\23\1\24"+
    "\36\23\33\24\2\0\3\23\60\0\46\23\13\24\1\23\u014f\0\3\24"+
    "\66\23\2\0\1\24\1\23\20\24\2\0\1\23\4\24\3\0\12\23"+
    "\2\24\2\0\12\24\21\0\3\24\1\0\10\23\2\0\2\23\2\0"+
    "\26\23\1\0\7\23\1\0\1\23\3\0\4\23\2\0\1\24\1\23"+
    "\7\24\2\0\2\24\2\0\3\24\11\0\1\24\4\0\2\23\1\0"+
    "\3\23\2\24\2\0\12\24\4\23\15\0\3\24\1\0\6\23\4\0"+
    "\2\23\2\0\26\23\1\0\7\23\1\0\2\23\1\0\2\23\1\0"+
    "\2\23\2\0\1\24\1\0\5\24\4\0\2\24\2\0\3\24\13\0"+
    "\4\23\1\0\1\23\7\0\14\24\3\23\14\0\3\24\1\0\11\23"+
    "\1\0\3\23\1\0\26\23\1\0\7\23\1\0\2\23\1\0\5\23"+
    "\2\0\1\24\1\23\10\24\1\0\3\24\1\0\3\24\2\0\1\23"+
    "\17\0\2\23\2\24\2\0\12\24\1\0\1\23\17\0\3\24\1\0"+
    "\10\23\2\0\2\23\2\0\26\23\1\0\7\23\1\0\2\23\1\0"+
    "\5\23\2\0\1\24\1\23\6\24\3\0\2\24\2\0\3\24\10\0"+
    "\2\24\4\0\2\23\1\0\3\23\4\0\12\24\1\0\1\23\20\0"+
    "\1\24\1\23\1\0\6\23\3\0\3\23\1\0\4\23\3\0\2\23"+
    "\1\0\1\23\1\0\2\23\3\0\2\23\3\0\3\23\3\0\10\23"+
    "\1\0\3\23\4\0\5\24\3\0\3\24\1\0\4\24\11\0\1\24"+
    "\17\0\11\24\11\0\1\23\7\0\3\24\1\0\10\23\1\0\3\23"+
    "\1\0\27\23\1\0\12\23\1\0\5\23\4\0\7\24\1\0\3\24"+
    "\1\0\4\24\7\0\2\24\11\0\2\23\4\0\12\24\22\0\2\24"+
    "\1\0\10\23\1\0\3\23\1\0\27\23\1\0\12\23\1\0\5\23"+
    "\2\0\1\24\1\23\7\24\1\0\3\24\1\0\4\24\7\0\2\24"+
    "\7\0\1\23\1\0\2\23\4\0\12\24\22\0\2\24\1\0\10\23"+
    "\1\0\3\23\1\0\27\23\1\0\20\23\4\0\6\24\2\0\3\24"+
    "\1\0\4\24\11\0\1\24\10\0\2\23\4\0\12\24\22\0\2\24"+
    "\1\0\22\23\3\0\30\23\1\0\11\23\1\0\1\23\2\0\7\23"+
    "\3\0\1\24\4\0\6\24\1\0\1\24\1\0\10\24\22\0\2\24"+
    "\15\0\60\23\1\24\2\23\7\24\4\0\10\23\10\24\1\0\12\24"+
    "\47\0\2\23\1\0\1\23\2\0\2\23\1\0\1\23\2\0\1\23"+
    "\6\0\4\23\1\0\7\23\1\0\3\23\1\0\1\23\1\0\1\23"+
    "\2\0\2\23\1\0\4\23\1\24\2\23\6\24\1\0\2\24\1\23"+
    "\2\0\5\23\1\0\1\23\1\0\6\24\2\0\12\24\2\0\2\23"+
    "\42\0\1\23\27\0\2\24\6\0\12\24\13\0\1\24\1\0\1\24"+
    "\1\0\1\24\4\0\2\24\10\23\1\0\42\23\6\0\24\24\1\0"+
    "\2\24\4\23\4\0\10\24\1\0\44\24\11\0\1\24\71\0\42\23"+
    "\1\0\5\23\1\0\2\23\1\0\7\24\3\0\4\24\6\0\12\24"+
    "\6\0\6\23\4\24\106\0\46\23\12\0\51\23\7\0\132\23\5\0"+
    "\104\23\5\0\122\23\6\0\7\23\1\0\77\23\1\0\1\23\1\0"+
    "\4\23\2\0\7\23\1\0\1\23\1\0\4\23\2\0\47\23\1\0"+
    "\1\23\1\0\4\23\2\0\37\23\1\0\1\23\1\0\4\23\2\0"+
    "\7\23\1\0\1\23\1\0\4\23\2\0\7\23\1\0\7\23\1\0"+
    "\27\23\1\0\37\23\1\0\1\23\1\0\4\23\2\0\7\23\1\0"+
    "\47\23\1\0\23\23\16\0\11\24\56\0\125\23\14\0\u026c\23\2\0"+
    "\10\23\12\0\32\23\5\0\113\23\3\0\3\23\17\0\15\23\1\0"+
    "\4\23\3\24\13\0\22\23\3\24\13\0\22\23\2\24\14\0\15\23"+
    "\1\0\3\23\1\0\2\24\14\0\64\23\40\24\3\0\1\23\3\0"+
    "\2\23\1\24\2\0\12\24\41\0\3\24\2\0\12\24\6\0\130\23"+
    "\10\0\51\23\1\24\126\0\35\23\3\0\14\24\4\0\14\24\12\0"+
    "\12\24\36\23\2\0\5\23\u038b\0\154\23\224\0\234\23\4\0\132\23"+
    "\6\0\26\23\2\0\6\23\2\0\46\23\2\0\6\23\2\0\10\23"+
    "\1\0\1\23\1\0\1\23\1\0\1\23\1\0\37\23\2\0\65\23"+
    "\1\0\7\23\1\0\1\23\3\0\3\23\1\0\7\23\3\0\4\23"+
    "\2\0\6\23\4\0\15\23\5\0\3\23\1\0\7\23\17\0\4\24"+
    "\32\0\5\24\20\0\2\23\23\0\1\23\13\0\4\24\6\0\6\24"+
    "\1\0\1\23\15\0\1\23\40\0\22\23\36\0\15\24\4\0\1\24"+
    "\3\0\6\24\27\0\1\23\4\0\1\23\2\0\12\23\1\0\1\23"+
    "\3\0\5\23\6\0\1\23\1\0\1\23\1\0\1\23\1\0\4\23"+
    "\1\0\3\23\1\0\7\23\3\0\3\23\5\0\5\23\26\0\44\23"+
    "\u0e81\0\3\23\31\0\11\23\6\24\1\0\5\23\2\0\5\23\4\0"+
    "\126\23\2\0\2\24\2\0\3\23\1\0\137\23\5\0\50\23\4\0"+
    "\136\23\21\0\30\23\70\0\20\23\u0200\0\u19b6\23\112\0\u51a6\23\132\0"+
    "\u048d\23\u0773\0\u2ba4\23\u215c\0\u012e\23\2\0\73\23\225\0\7\23\14\0"+
    "\5\23\5\0\1\23\1\24\12\23\1\0\15\23\1\0\5\23\1\0"+
    "\1\23\1\0\2\23\1\0\2\23\1\0\154\23\41\0\u016b\23\22\0"+
    "\100\23\2\0\66\23\50\0\15\23\3\0\20\24\20\0\4\24\17\0"+
    "\2\23\30\0\3\23\31\0\1\23\6\0\5\23\1\0\207\23\2\0"+
    "\1\24\4\0\1\23\13\0\12\24\7\0\32\23\4\0\1\23\1\0"+
    "\32\23\12\0\132\23\3\0\6\23\2\0\6\23\2\0\6\23\2\0"+
    "\3\23\3\0\2\23\3\0\2\23\22\0\3\24\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\3\2\25\3\1\4\4\3\1\5";

  private static int [] zzUnpackAction() {
    int [] result = new int[32];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\25\0\52\0\77\0\25\0\124\0\151\0\176"+
    "\0\223\0\250\0\275\0\322\0\347\0\374\0\u0111\0\u0126"+
    "\0\u013b\0\u0150\0\u0165\0\u017a\0\u018f\0\u01a4\0\u01b9\0\u01ce"+
    "\0\u01e3\0\u01f8\0\151\0\u020d\0\u0222\0\u0237\0\u024c\0\151";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[32];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\7\7\1\10\4\7"+
    "\1\11\2\7\1\2\27\0\1\5\23\0\1\5\27\0"+
    "\1\7\1\12\17\7\4\0\21\7\4\0\11\7\1\13"+
    "\7\7\4\0\5\7\1\14\13\7\4\0\2\7\1\15"+
    "\16\7\4\0\12\7\1\16\6\7\4\0\2\7\1\17"+
    "\16\7\4\0\3\7\1\20\15\7\4\0\11\7\1\21"+
    "\7\7\4\0\7\7\1\22\11\7\4\0\4\7\1\23"+
    "\14\7\4\0\13\7\1\24\5\7\4\0\3\7\1\25"+
    "\15\7\4\0\5\7\1\26\13\7\4\0\12\7\1\27"+
    "\6\7\4\0\16\7\1\30\2\7\4\0\6\7\1\31"+
    "\12\7\4\0\11\7\1\32\7\7\4\0\7\7\1\33"+
    "\11\7\4\0\6\7\1\34\12\7\4\0\10\7\1\35"+
    "\10\7\4\0\3\7\1\36\15\7\4\0\14\7\1\20"+
    "\4\7\4\0\2\7\1\37\16\7\4\0\7\7\1\40"+
    "\11\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[609];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\33\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[32];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	StringBuffer string = new StringBuffer();

	private Symbol symbol(int type) {
		return new Symbol(type, yyline, yycolumn);
	}
	private Symbol symbol(int type, Object value) {
		return new Symbol(type, yyline, yycolumn, value);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnaliseLexicaOCL(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  AnaliseLexicaOCL(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1716) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 5: 
          { System.out.println("Comentário");
          }
        case 6: break;
        case 3: 
          { System.out.println("Identifier: ");
          }
        case 7: break;
        case 4: 
          { System.out.println("Keyword: context");
          }
        case 8: break;
        case 2: 
          { System.out.println("Espaço ou quebra de linha!");
          }
        case 9: break;
        case 1: 
          { System.out.print(yytext());
          }
        case 10: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java AnaliseLexicaOCL <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        AnaliseLexicaOCL scanner = null;
        try {
          scanner = new AnaliseLexicaOCL( new java.io.FileReader(argv[i]) );
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
