
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jul 25 13:35:26 EDT 1999
//----------------------------------------------------

package java_cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NON = 8;
  public static final int NONTERMINAL = 27;
  public static final int STAR = 15;
  public static final int SEMI = 13;
  public static final int CODE = 4;
  public static final int EOF = 0;
  public static final int NONASSOC = 23;
  public static final int LEFT = 21;
  public static final int WITH = 11;
  public static final int IMPORT = 3;
  public static final int error = 1;
  public static final int COLON_COLON_EQUALS = 18;
  public static final int SCAN = 10;
  public static final int ID = 28;
  public static final int INIT = 9;
  public static final int PARSER = 6;
  public static final int TERMINAL = 7;
  public static final int PRECEDENCE = 20;
  public static final int LBRACK = 25;
  public static final int RBRACK = 26;
  public static final int PERCENT_PREC = 24;
  public static final int START = 12;
  public static final int RIGHT = 22;
  public static final int ACTION = 5;
  public static final int CODE_STRING = 29;
  public static final int RIGHT_BRK = 16;
  public static final int LEFT_BRA = 14;
  public static final int UP_UP = 30;
  public static final int CONTEXT = 51;
  public static final int GT = 25;
  public static final int LT = 24;
  public static final int BAD = 1;
  public static final int RIGHT_BRA = 17;
  public static final int NOT = 38;
  public static final int AND = 37;
  public static final int INT_MOD = 42;
  public static final int LEFT_PAR = 12;
  public static final int COLLECTION = 41;
  public static final int UP = 11;
  public static final int TUPLE = 48;
  public static final int INT_DIVIDE = 39;
  public static final int PLUS = 9;
  public static final int TRUE = 44;
  public static final int RIGHT_PAR = 15;
  public static final int SIMPLE_NAME = 7;
  public static final int TIMES = 4;
  public static final int ELSE = 43;
  public static final int QUESTION = 22;
  public static final int THEN = 45;
  public static final int IF = 35;
  public static final int IMPLIES = 52;
  public static final int ENDIF = 47;
  public static final int OR = 34;
  public static final int BODY = 46;
  public static final int EQ = 23;
  public static final int AT = 21;
  public static final int SEMICOLON = 19;
  public static final int BAR = 20;
  public static final int COLON = 10;
  public static final int PACKAGE = 50;
  public static final int NE = 32;
  public static final int INTEGER = 6;
  public static final int XOR = 40;
  public static final int MINUS_GT = 26;
  public static final int MINUS = 5;
  public static final int DOT_DOT = 27;
  public static final int GE = 33;
  public static final int STRING = 28;
  public static final int DIVIDE = 3;
  public static final int PATHNAME = 29;
  public static final int COMMA = 18;
  public static final int LEFT_BRK = 13;
  public static final int REAL = 36;
  public static final int LE = 31;
  public static final int FALSE = 49;
  public static final int ENDPACKAGE = 53;
  public static final int DOT = 8;
  public static final int BAG = 42;
  public static final int SEQUENCE = 54;
  public static final int SET = 41;
  public static final int ORDEREDSET = 47;
  
  
  // Definições dos tokens- segue o padrão 987 (numero qualquer)
  
  public static final int OPERATOR = 9871;
  public static final int KEYWORD = 9872;
  public static final int TYPE = 9873;
  public static final int BOOLEAN = 9874;
  public static final int IDENTIFIER = 9875;
  public static final int BOOLEANOPERATOR = 25;
public static final int EQEQ = 0;
public static final int BREAK = 0;
public static final int INTEGER_LITERAL = 0;
	public static final int ABSTRACT = 0;
	public static final int STRING_LITERAL = 0;
  
 
}

